/*
  Name:             keybd_shift
  Copyright:        Copyright (C) SIL International.
  Documentation:
  Description:
  Create Date:      11 Dec 2009

  Modified Date:    9 Aug 2015
  Authors:          mcdurdin
  Related Files:
  Dependencies:

  Bugs:
  Todo:
  Notes:
  History:          11 Dec 2009 - mcdurdin - I934 - x64 - Initial version
                    12 Mar 2010 - mcdurdin - I934 - x64 - Complete
                    12 Mar 2010 - mcdurdin - I2229 - Remove hints and warnings
                    31 Dec 2014 - mcdurdin - I4548 - V9.0 - When Alt is down, release of Ctrl, Shift is not detectable within TIP in some languages
                    09 Aug 2015 - mcdurdin - I4844 - Tidy up PostDummyKeyEvent calls
*/
#include "pch.h"
#include "kbd.h"

/**
  The modifier virtual keys Keyman manages. Every modifier loop iterates this table, and
  KEYMAN_MODIFIER_VK_COUNT derives MAX_KEYEVENT_INPUTS_MODIFIERS, so adding one is a single edit.

  Not the low level hook's accepted-VK set: that is nine VKs (isModifierKey, guarded by
  IsModifierKeyAcceptsExactlyNineVks) which collapse into these six. Do not unify them.
*/
const BYTE KeymanModifierVks[KEYMAN_MODIFIER_VK_COUNT] = {
  VK_LMENU, VK_RMENU, VK_LCONTROL, VK_RCONTROL, VK_LSHIFT, VK_RSHIFT
};

/**
  do_keybd_event adds a keyboard event into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  This function mimics the keybd_event Windows API function, but instead of posting the event
  to the system keyboard event queue, it appends it to our internal event queue in pInputs.
  This allows us to send an atomic set of key events with SendInput.

  In this function, we map back the extended modifier keys. Now, the history of the PC keyboard
  means that this is a little weird. The original PC XT keyboard had Left and Right Shift keys,
  but only a single Ctrl and a single Alt key. This means, that the shift keys were each assigned
  their own scan code. However, Windows maps both keys to the same virtual key code (VK_SHIFT) for
  most purposes.

  When the Right Ctrl and Right Alt keys were introduced, they were differentiated from the original
  keys not by separate scan codes, but by an extended prefix byte (E0), together with the original
  scan code. Again, Windows does not differentiate with virtual keys (VK_CONTROL and VK_MENU).

  This means, to check for Left vs Right Shift, you need to test the scan code (2A and 36)
  respectively. However, to test for Left vs Right Ctrl/Alt, you need to test the Extended bit in
  the flags for the message.

  There are a few places where VK_LSHIFT, VK_RSHIFT, VK_LCONTROL, VK_RCONTROL, VK_LMENU, and
  VK_RMENU can be used, such as GetKeyState or MapVirtualKey. However, these virtual key codes
  should never be emitted and will never be received as a key event.

  To add an additional wrinkle to an already wrinkly story, Keyman (ab)uses the scan code property
  of key events to identify key events that it has synthesized, as opposed to those generated by
  the user or by another app (e.g. Remote Desktop scenarios). Instead of using the correct scan
  code, it will stuff the key event with a 0xFF scan code, and replace that in its GetMessage
  so the end application gets a look at the correct scan code. However, this will obviously not
  work with Right Shift, which is differentiated from Left Shift _only_ by scan code. Fortunately,
  we can afford to not care about this -- it means a little extra flag setting behind the scenes
  as the right shift key is released and re-pressed during key events, but nothing too dramatic.
*/
void do_keybd_event(LPINPUT pInputs, int *n, BYTE vk, BYTE scan, DWORD flags, ULONG_PTR extraInfo) {   // I4548
  INPUT input;
  input.type = INPUT_KEYBOARD;

  switch(vk) {
  case VK_RCONTROL:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LCONTROL:
    vk = VK_CONTROL;
    break;

  case VK_RMENU:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LMENU:
    vk = VK_MENU;
    break;

  case VK_RSHIFT:
    scan = SCANCODE_RSHIFT; // from kbd.h
    /*fallthrough*/
  case VK_LSHIFT:
    vk = VK_SHIFT;
    break;
  }

  input.ki.wVk = vk;
  input.ki.wScan = scan;
  input.ki.dwFlags = flags;
  input.ki.time = 0;
  input.ki.dwExtraInfo = extraInfo;
  SendDebugMessageFormat("n=%d, vk=%s, scan=%x, flags=%x", *n, Debug_VirtualKey(vk), scan, flags);

  pInputs[*n] = input;
  (*n)++;
}

/**
  keybd_sendprefix pushes a dummy keystroke into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  The keybd_sendprefix call is needed, for example, if the user presses Alt+F which matches a rule
  in the current Keyman keyboard, because without the dummy prefix key, faking the release of the
  Alt key will activate the mainmenu of the current application.
*/
void keybd_sendprefix(LPINPUT pInputs, int *n)
{
  SendDebugEntry();
  //SendDebugMessageFormat("sending prefix down+up");
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, 0, 0);   // I4548   // I4844
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, 0);   // I4548   // I4844
  SendDebugExit();
}

/**
  keybd_shift_release records the current keyboard state and then releases any modifier
  keys. If a modifier key must be released, it first sends a dummy prefix key to prevent
  isolated modifier key actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), in which we will store
                       the initial modifier state for later restoration by keybd_shift_reset
*/
void keybd_shift_release(LPINPUT pInputs, int *n, LPBYTE const kbd) {
  BOOL hasSentPrefix = FALSE;

  SendDebugEntry();
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      if (!hasSentPrefix) {
        keybd_sendprefix(pInputs, n);
        hasSentPrefix = TRUE;
      }
      SendDebugMessageFormat("sending keyup vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP);
    }
  }
  SendDebugExit();
}

/**
  keybd_shift_reset returns the modifiers to their original pressed state and, if any modifier
  key presses are emitted, emits also a dummy 'prefix' keystroke in order to prevent default
  modifier actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), previously set by
                       keybd_shift_release
*/
void keybd_shift_reset(LPINPUT pInputs, int *n, LPBYTE const kbd) {
  BOOL needsPrefix = FALSE;

  SendDebugEntry();
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      SendDebugMessageFormat("sending keydown vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, 0, EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP);
      needsPrefix = TRUE;
    }
  }

  if (needsPrefix) {
    keybd_sendprefix(pInputs, n);
  }
  SendDebugExit();
}

/**
  keybd_shift evaluates the current keyboard modifier state and queues key events in order to
  initially set modifiers to "up" and, after the output key events are queued, resets the modifiers
  to their initial state.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              isReset  are we clearing or resetting the modifier state?
              kbd      pointer to keyboard state (256 byte array) that owner must maintain but
                       that we will fill

  There must be enough space in pInputs to contain 6 x up + 6 x down + 2 prefix-down + 2 prefix-up event = 16 events,
  to support both the clear and reset calls.
*/
void keybd_shift(LPINPUT pInputs, int *n, BOOL isReset, LPBYTE const kbd) {
  if (isReset) {
    keybd_shift_reset(pInputs, n, kbd);
  } else {
    keybd_shift_release(pInputs, n, kbd);
  }
}


/**
  CaptureLiveModifierState takes one reading per managed modifier into liveOut.

  Parameters: liveOut              256 bytes, 0x80 for each modifier the OS reports held
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  The single acquisition point for live state in a batch. Everything downstream reads liveOut, so
  the reconcile and the release set are computed from one snapshot. A reading per consumer let the
  two disagree -- the user can press or release in between -- and a batch assembled from two
  snapshots can release a modifier and then decline to restore it. Exactly
  KEYMAN_MODIFIER_VK_COUNT readings, pinned by BatchTakesOneLiveReadingPerManagedModifier.

  GetAsyncKeyState, not GetKeyState or GetKeyboardState: those read the calling thread's processed
  queue, the stale source.

  Not a gap, measured: SendInput does not return until the injected press is visible to
  GetAsyncKeyState, so a previous batch's re-press cannot still be in flight here. Pinned by
  DISABLED_ReconcileDoesNotRaceItsOwnInjectedRestorePress, which also records what would break.

  Residual gaps Task 3 -- considered and deliberately not widened to the three generic VKs
  (VK_SHIFT, VK_CONTROL, VK_MENU) that isModifierKey also accepts. UpdateModifierCacheFromKeyEvent
  has to handle them because that is a hook feed, and a third party can inject anything; this
  function does not, because GetAsyncKeyState(VK_LSHIFT)/(VK_RSHIFT) etc. is expected to already
  reflect a generic injection. DISABLED_DwExtraInfoSurvivesSendInputWhereTheScanCodeDoesNot measured
  that do_keybd_event's own generic-to-chiral collapse (VK_LSHIFT -> VK_SHIFT + a scan code) arrives
  back at the hook re-chiralised (vkCode 0xA0/0xA1, not 0x10) before the hook ever sees it, which
  means Windows resolves chirality from the scan code on the way in, not on the way out through
  GetAsyncKeyState. A generic-VK-press-then-reconcile path is characterised without any code change
  by MODIFIER_CACHE_EVENT_ORDER.GenericVkEventReconcilesAgainstTheChiralLiveReading, and
  DISABLED_GenericShiftSendInputReflectsInBothAsyncKeyStates is the live measurement of the specific
  claim this rests on -- a third party's own SendInput with a generic wVk and scan 0. If that probe
  ever shows GetAsyncKeyState(VK_LSHIFT) and (VK_RSHIFT) both false while GetAsyncKeyState(VK_SHIFT)
  is true, this function needs a fallback: OR the generic reading into both chiral halves when
  neither already reports held. That direction is safe to add later without redesign -- over-
  reporting live state can only add an extra release or an extra reconcile-clear, never an unmatched
  KEYDOWN -- but it was not added speculatively here, because it would cost three more reader calls
  every batch (breaking the "exactly six" invariant above) against a claim the existing measurement
  already argues does not hold in practice.
*/
void CaptureLiveModifierState(LPBYTE liveOut, PGETASYNCKEYSTATE pfnGetAsyncKeyState) {
  // Zeroed in full: no caller stack residue is mistaken for a held modifier.
  memset(liveOut, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (pfnGetAsyncKeyState(KeymanModifierVks[i]) < 0) {
      liveOut[KeymanModifierVks[i]] = 0x80;
    }
  }
}

/**
  ReconcileModifierCache clears any modifier the cache reports held while the live state reports it
  up. Returns TRUE if the two disagreed.

  Parameters: kbd   the modifier cache (256 byte array), reconciled in place
              live  the live snapshot from CaptureLiveModifierState. Read, never written

  A dropped modifier KEYUP leaves that cache byte set for the life of the process, and
  keybd_shift_reset then presses the modifier for real. See #8064.

  Clears but never sets, since the user may release before SendInput runs.
*/
BOOL ReconcileModifierCache(LPBYTE const kbd, LPBYTE const live) {
  BOOL disagreed = FALSE;

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    const BYTE vk = KeymanModifierVks[i];
    if ((kbd[vk] & 0x80) && !(live[vk] & 0x80)) {
      SendDebugMessageFormat("cache says held but OS says up, clearing vkey=%s", Debug_VirtualKey(vk));
      kbd[vk] = 0;
      disagreed = TRUE;
    }
  }

  return disagreed;
}

/**
  ComputeModifierReleaseState fills releaseStateOut with the union of the modifiers the cache holds
  and the modifiers the OS holds.

  Parameters: kbd              the modifier cache (256 bytes). Read, never written
              releaseStateOut  256 bytes, the release set. Must not alias kbd
              live             the live snapshot from CaptureLiveModifierState. Read, never written

  The mirror of #8064: a modifier the OS holds that the cache never saw would otherwise let the
  batch inject its output keys with that modifier live. The union is explicit so that removing the
  reconcile cannot quietly make this a cache-only read.
*/
void ComputeModifierReleaseState(LPBYTE const kbd, LPBYTE releaseStateOut, LPBYTE const live) {
  // Zeroed in full: no caller stack residue reaches keybd_shift_release.
  memset(releaseStateOut, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    const BYTE vk = KeymanModifierVks[i];
    if ((kbd[vk] & 0x80) || (live[vk] & 0x80)) {
      releaseStateOut[vk] = 0x80;
    }
  }
}

/**
  PrepareInjectedInputBatch assembles one injected batch into pInputs and returns the event count:
  release half, output keys, restore half.

  Parameters: pInputs              at least MAX_KEYEVENT_INPUTS INPUT structures
              kbd                  the modifier cache (256 bytes), reconciled in place
              pSharedData          the output keys to wrap; nInputs is clamped here
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState
              cacheIsFed           see "residual gaps Task 2" below. Default TRUE so existing
                                   callers (and every pre-existing test) are unaffected
              pRestorePressedMask  see "residual gaps Task 1" below. Optional, default NULL

  A free function so the gtest project can reach it; serialkeyeventserver.cpp is #ifndef _WIN64.
  The output-key copy stops MAX_KEYEVENT_INPUTS_MODIFIERS short of the end so the restore half
  fits: the worst case fills the buffer exactly, so an off-by-one is a heap overrun. See #8064.

  Residual gaps Task 2 -- cacheIsFed. ComputeModifierReleaseState's union is only sound when the
  cache is actually being fed by the low level hook's WM_KEYMAN_MODIFIER_EVENT post, which is
  itself gated on flag_ShouldSerializeInput (k32_lowlevelkeyboardhook.cpp). With that flag off, the
  cache never learns anything after its one-time launch seed, so a live-driven release the union
  adds can never be balanced by a later batch's restore -- the restore half reads kbd, and kbd stays
  exactly as stale as it started. That is a genuinely new lost-modifier regression the union
  introduces: before it existed, release and restore both read the same (stale) kbd and so stayed
  symmetric, which is why "an unfed cache meant no wrap at all" pre-#8064. cacheIsFed makes that
  precondition explicit: FALSE degrades the release set back to a plain copy of kbd, restoring that
  symmetry and the pre-union behaviour (including its own, separate #8064 exposure, which is the
  flag's pre-existing, documented trade-off and not something this task introduces or fixes).

  Residual gaps Task 1 -- pRestorePressedMask. If non-NULL, receives a bitmask over
  KeymanModifierVks (bit i set iff KeymanModifierVks[i] was pressed by this call's restore half).
  keybd_shift_reset only ever reads kbd, never writes it, so this is exactly kbd's post-reconcile
  state restricted to the managed set -- read after the restore call purely so the intent at the
  read site is unambiguous, not because the restore could have changed it. The caller uses this to
  scope a post-batch verification pass to only the VKs this batch actually touched. See
  PrepareModifierVerificationCorrection.
*/
int PrepareInjectedInputBatch(
  LPINPUT pInputs,
  LPBYTE const kbd,
  const SerialKeyEventSharedData *pSharedData,
  PGETASYNCKEYSTATE pfnGetAsyncKeyState,
  BOOL cacheIsFed,
  DWORD *pRestorePressedMask) {
  DWORD nInputs = min(pSharedData->nInputs, MAX_KEYEVENT_INPUTS);
  int n         = 0;

  // One reading per modifier for the whole batch. Both consumers below read this, so they cannot
  // disagree about what the OS held at the top of the batch.
  BYTE live[256];
  CaptureLiveModifierState(live, pfnGetAsyncKeyState);

  // Clear any modifier the cache thinks is held but the OS does not, before keybd_shift_reset
  // below presses it for real. See #8064. Safe regardless of cacheIsFed: this only ever clears a
  // byte, which can only turn into a skipped restore or an extra release, never a press.
  ReconcileModifierCache(kbd, live);

  // Locals, never member state: a second long-lived cache is a second thing to keep in sync.
  BYTE releaseState[256];
  if (cacheIsFed) {
    ComputeModifierReleaseState(kbd, releaseState, live);
  } else {
    // Task 2: the union is unsound here -- see the function comment above. Falling back to a bare
    // copy of kbd keeps the release half reading exactly what the restore half reads, so the two
    // stay symmetric even though the cache itself may be stale.
    memcpy(releaseState, kbd, 256);
  }

  keybd_shift(pInputs, &n, FALSE, releaseState);

  for (DWORD i = 0; i < nInputs && n < MAX_KEYEVENT_INPUTS - MAX_KEYEVENT_INPUTS_MODIFIERS; i++, n++) {
    pInputs[n].type           = INPUT_KEYBOARD;
    pInputs[n].ki.wVk         = pSharedData->inputs[i].wVk;
    pInputs[n].ki.wScan       = pSharedData->inputs[i].wScan;
    pInputs[n].ki.dwFlags     = pSharedData->inputs[i].dwFlags;
    pInputs[n].ki.time        = pSharedData->inputs[i].time;
    pInputs[n].ki.dwExtraInfo = (ULONG_PTR)pSharedData->inputs[i].extraInfo;
  }

  // Not reconciled here: mid-batch the OS state is Keyman's own doing, not ground truth. And kbd,
  // never releaseState -- re-pressing on the OS's word is unsafe, since the user may let go before
  // SendInput runs. That unmatched KEYDOWN is #8064.
  keybd_shift(pInputs, &n, TRUE, kbd);

  if (pRestorePressedMask != NULL) {
    DWORD mask = 0;
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      if (kbd[KeymanModifierVks[i]] & 0x80) {
        mask |= (1u << i);
      }
    }
    *pRestorePressedMask = mask;
  }

  return n;
}

/**
  PrepareModifierVerificationCorrection builds the post-batch verification pass for the residual
  gaps left by the batch-level reconcile: a pass-through race (mstsc/RDP, the touch panel, console
  focus, or GetGUIThreadInfo failure all route the user's real modifier events around the "eat and
  re-inject" path at the hook, so their ordering relative to a batch's own SendInput is not under
  Keyman's control) and the accepted C-9/G1 window (the user physically releases while a batch is in
  flight). Both leave the same residue: the batch's own restore press outlives a user release that
  raced it, the cache correctly learns the release (because it is the user's own event, not
  Keyman's), but the OS is left holding the modifier -- cache says up, OS says held. Nothing in the
  current batch can detect that; ReconcileModifierCache is defined to fix exactly this disagreement,
  but only on the *next* batch, and only if one arrives. If the chord that produced this batch was
  the end of a typing burst, or the user switches app or keyboard, no next batch ever comes and the
  OS holds the modifier indefinitely. This function is what closes that window without waiting for
  one.

  Parameters: pInputs              at least MAX_KEYEVENT_INPUTS_MODIFIERS INPUT structures
              kbd                  the modifier cache (256 bytes), read only -- the CURRENT cache,
                                   not a snapshot from when the batch was built. By the time this
                                   runs (see the caller, and the comment on
                                   WM_KEYMAN_VERIFY_MODIFIER_EVENT in serialkeyeventcommon.h, for why
                                   it is safe to rely on "current"), every modifier event the hook
                                   posted before this verification was itself posted has already
                                   been applied here
              restorePressedMask   bit i set iff KeymanModifierVks[i] was pressed by the batch this
                                   verification follows -- PrepareInjectedInputBatch's out-param,
                                   carried through the verify message's wParam. Restricts the check
                                   to the VKs that batch actually touched; a VK outside this mask is
                                   left alone even if it happens to disagree, because that
                                   disagreement, if any, belongs to some other batch
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  For each VK in restorePressedMask: if the cache now says up but the OS reports it held, the OS is
  holding a modifier nobody holds, and the correction is a KEYUP. Built via keybd_shift_release
  rather than emitted directly, so it gets the same prefix protection (an isolated Alt release opens
  the window menu) and the same EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP / SCAN_FLAG_KEYMAN_KEY_EVENT
  tagging that keeps the correction itself out of the cache.

  Known residual, and it is the reason this is a correction pass rather than a certainty: if
  the user presses that same modifier again in the handful of milliseconds after the verify message
  is posted, their fresh KEYDOWN is queued in this thread's message queue behind the verify message
  (FIFO), so it has not yet reached the cache when this runs. This function then sees cache-up /
  OS-held and "corrects" a hold that has, by the time the correction lands, become genuine again --
  releasing the user's real press. That is the cheaper error: an unmatched KEYUP is recoverable by
  re-pressing, where an unmatched KEYDOWN may not be (an extended Right Ctrl on hardware with no
  physical Right Ctrl key cannot be cleared by any keystroke the user can produce). Widening this to
  also *set* cache bytes to avoid the false positive would reintroduce exactly that unmatched-KEYDOWN
  risk from a third direction; see ReconcileModifierCache's own "clears but never sets" rule, which
  this deliberately mirrors.
*/
int PrepareModifierVerificationCorrection(
  LPINPUT pInputs,
  LPBYTE const kbd,
  DWORD restorePressedMask,
  PGETASYNCKEYSTATE pfnGetAsyncKeyState) {
  int n = 0;

  BYTE live[256];
  CaptureLiveModifierState(live, pfnGetAsyncKeyState);

  BYTE correction[256];
  memset(correction, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (!(restorePressedMask & (1u << i))) {
      continue; // outside the set this batch touched -- not this verification's problem
    }
    const BYTE vk = KeymanModifierVks[i];
    if (!(kbd[vk] & 0x80) && (live[vk] & 0x80)) {
      SendDebugMessageFormat("verification: OS holds vkey=%s that the cache says nobody holds, correcting", Debug_VirtualKey(vk));
      correction[vk] = 0x80;
    }
  }

  keybd_shift_release(pInputs, &n, correction);

  return n;
}

/**
  UpdateModifierCacheFromKeyEvent applies one modifier key event to the cache, collapsing the
  hook's VKs onto the chiral pair the cache is keyed by.

  Parameters: kbd              the modifier cache (256 bytes), updated in place
              bVk              the event's virtual key as the hook reported it
              fIsExtendedKey   the event's KEYEVENTF_EXTENDEDKEY flag
              bScan            the event's scan code; for VK_SHIFT this is the only chirality signal
              fIsUp            TRUE for a KEYUP

  Applies every modifier event the hook posts, including Keyman's own injected ones: the post at
  k32_lowlevelkeyboardhook.cpp:196 runs before the "generated by Keyman" pass-through at :224, so
  the cache is not a record of what the user is physically holding. A balanced batch cancels out --
  the release half's KEYUP and the restore half's KEYDOWN net to the original byte -- so this is
  invisible until a real user event interleaves. See
  KeymanOwnRestorePressOutlivesTheUsersRealRelease for what that costs.
*/
void UpdateModifierCacheFromKeyEvent(LPBYTE kbd, BYTE bVk, BOOL fIsExtendedKey, BYTE bScan, BOOL fIsUp) {
  switch (bVk) {
  case VK_CONTROL:
    // Left and right control are distinguished by a 0xE0 prefix byte
    bVk = fIsExtendedKey ? VK_RCONTROL : VK_LCONTROL;
    break;
  case VK_MENU:
    // Left and right alt are distinguished by a 0xE0 prefix byte
    bVk = fIsExtendedKey ? VK_RMENU : VK_LMENU;
    break;
  case VK_SHIFT:
    // Left and right shift are distinguished by scan code alone
    bVk = bScan == SCANCODE_RSHIFT ? VK_RSHIFT : VK_LSHIFT;
    break;
  case VK_LCONTROL:
  case VK_RCONTROL:
  case VK_LSHIFT:
  case VK_RSHIFT:
  case VK_LMENU:
  case VK_RMENU:
    // These are technically not needed but perhaps some app will send them through SendInput
    // and we'll have to deal with them?
    break;
  default:
    return;
  }

  kbd[bVk] = fIsUp ? 0 : 0x80;
}

/**
  IsKeymanInjectedKeyEvent reports whether a key event the low level hook received was injected by
  Keyman itself rather than produced by the user's keyboard.

  Parameters: scanCode   the event's scan code as the hook reported it
              extraInfo  the event's dwExtraInfo as the hook reported it

  Two arms, because neither covers the managed set alone:

  - scanCode == SCAN_FLAG_KEYMAN_KEY_EVENT catches every event Keyman injects with the 0xFF scan
    overload, including the keybd_event callers that cannot set dwExtraInfo at all
    (kmhook_keyboard.cpp:147). This arm is not legacy: keybd_event has no extraInfo parameter, so
    it cannot be deprecated away while those callers exist.
  - extraInfo == EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP catches Right Shift, whose 0xFF scan is
    overwritten with SCANCODE_RSHIFT by do_keybd_event because 0x36 is how the receiving app knows
    which Shift it was. Measured to survive SendInput to the hook by
    DISABLED_DwExtraInfoSurvivesSendInputWhereTheScanCodeDoesNot.

  Equality on the tag, never extraInfo != 0. mstsc stamps 0x4321DCBA on genuine remote user input
  and other injectors stamp their own values; treating any non-zero value as Keyman's would blind
  the modifier cache to a remote user's real modifiers, and the next batch would strip them.

  Deliberately does not match EXTRAINFO_FLAG_SERIALIZED_USER_KEY_EVENT. Those are user keystrokes
  Keyman re-injected, not Keyman's own synthetic modifiers, and the server already applies them to
  the cache directly, so the echo is an idempotent duplicate rather than a corruption.

  Says nothing about LLKHF_INJECTED. That flag is set by every injector, the On-Screen Keyboard
  included, and an OSK sticky modifier is meant to be real machine-wide. Filtering on it would
  strip it. See #8064.
*/
BOOL IsKeymanInjectedKeyEvent(DWORD scanCode, ULONG_PTR extraInfo) {
  return scanCode == SCAN_FLAG_KEYMAN_KEY_EVENT || extraInfo == EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP;
}
